<?php

	$language = isset($_GET['language']) ? $_GET['language'] : false;

	$languagePackage = array(
		'pt' => array(
			'site_title' => "Liberdade Já!",
			'site_long_title' => 'Liberdade aos Presos Políticos em Angola',
			'site_description' => "Contra as prisões políticas dos 15 activistas angolanos. Pela liberdade e a democracia em Angola. Freedom for the Political Prisoners in Angola.",
			'dias_presos' => "dias presos",
			'greve_fome' => "de greve<br>de fome",
			'quero_participar' => "<span>Eu</span>Quero<br>Participar!",
			'ler_quem_somos' => "<span>ler</span><span>Quem<br>somos</span>",
			'visita_nos_facebook' => "<span><em>Visita-nos</em><br>no<br>Facebook</span>",
			'politica_privacidade' => "<span>Política<br>de<br>Privacidade</span>",
			'proximo' => 'Ver próximo',
			'participar' => "Participar!",
			'fechar' => 'fechar',
			'enviar_foto_apelo' => 'Enviar foto com <span class="underline">apelo escrito</span>',
			'agradecemos_permissao' => 'Agradecemos permissao para',
			'seleccionar_foto' => "Clique para selecionar foto...",
			'mensagem_partilha_facebook' => 'Mensagem para partilha no facebook aqui...',
			'partilhar_apelo_facebook' => "Partilhar este apelo no facebook",
			'enviar_para_entidades' => 'Enviar o apelo para as entidades competentes',
			'qual_nome_email' => 'Qual o teu nome e email ?',
			'form_nome' => "nome",
			'form_email' => "email",
			'form_nome_placeholder' => 'Name here...',
			'form_email_placeholder' => 'Your e-mail...',
			'form_preview_email' => 'Click para ver o conteudo do email a enviar',
			'form_about_photo_approvals' => 'A tua foto será aprovada e publicada automaticamente neste site, se o post no Facebook for seleccionado. As restantes, ficam pendentes e publicadas após aprovação. Obrigado pelo apoio!',
			'form_confirmar' => "confirmar",
			'form_success_message' => "O seu apelo foi registado com sucesso.<br>Obrigado!",
			'email_preview_your_name_here' => "* O seu nome aqui",
			'email_preview_about_this_photo' => "* Esta foto é um exemplo, pois será utilizada a foto-apelo que irá partilhar ao clicar no botão confirmar do formulário."
		),

		'en' => array(
			'site_title' => "Freedom now!",
			'site_long_title' => 'Liberdade aos Presos Políticos em Angola',
			'site_description' => "Against the political arrests of 15 Angolan activists. For the freedom and democracy in Angola.",
			'dias_presos' => "days imprisoned",
			'greve_fome' => "on hunger<br>strike",
			'quero_participar' => "<span>I</span>want to<br>Participate!",
			'ler_quem_somos' => "<span>About</span><span>Who<br>we are</span>",
			'visita_nos_facebook' => "<span><em>Visit us</em><br>on<br>Facebook</span>",
			'politica_privacidade' => "<span>Privacy<br>Policy</span>",
			'proximo' => 'Next',
			'participar' => "Participate!",
			'fechar' => 'close',
			'enviar_foto_apelo' => 'Send your <span class="underline">photo appeal</span>',
			'agradecemos_permissao' => 'We\'d appreciate your permission to',
			'seleccionar_foto' => "Click to select a photo...",
			'mensagem_partilha_facebook' => 'Your message for your Facebook share...',
			'partilhar_apelo_facebook' => "Share this appeal on Facebook",
			'enviar_para_entidades' => 'Send the appeal to the competent authorities',
			'qual_nome_email' => 'What\'s your name & email address ?',
			'form_nome' => "name",
			'form_email' => "email",
			'form_nome_placeholder' => 'Name here...',
			'form_email_placeholder' => 'Your e-mail...',
			'form_preview_email' => 'Click to preview the email that we\'ll send',
			'form_about_photo_approvals' => 'Your photo will be published imediately if you\'ve accepted sharing on Facebook. Otherwise they\'ll  be published after an approval process. Thanks for your support!',
			'form_confirmar' => "confirm",
			'form_success_message' => "Your appeal was sent successfully!<br>Thank you!",
			'email_preview_your_name_here' => "* Your name here",
			'email_preview_about_this_photo' => "* Photo example, the photo you share will be used instead."
		)

	);